export const SERVICE_REQUEST_STATUSES = {
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  COMPLETED: "COMPLETED",
};

export const SERVICE_REQUEST_STATUS_VALUES = Object.values(
  SERVICE_REQUEST_STATUSES
);

export const SERVICE_REQUEST_TRANSITIONS = {
  [SERVICE_REQUEST_STATUSES.PENDING]: new Set([
    SERVICE_REQUEST_STATUSES.APPROVED,
    SERVICE_REQUEST_STATUSES.REJECTED,
  ]),
  [SERVICE_REQUEST_STATUSES.APPROVED]: new Set([
    SERVICE_REQUEST_STATUSES.COMPLETED,
  ]),
  [SERVICE_REQUEST_STATUSES.REJECTED]: new Set(),
  [SERVICE_REQUEST_STATUSES.COMPLETED]: new Set(),
};
